//
//  Home.swift
//  AvanceProyecto
//
//  Created by Alumno on 28/08/25.
//

import SwiftUI

struct Home: View {
  var body: some View {
    ZStack() {
      Group {
        ZStack() {
          ZStack() {

          }
          .frame(width: 30, height: 30)
          .offset(x: -142, y: 0)
          Text("Search crops...")
            .font(Font.custom("Inria Sans", size: 20).weight(.bold))
            .foregroundColor(Color(red: 0, green: 0, blue: 0).opacity(0.15))
            .offset(x: 15, y: -1.50)
        }
        .frame(width: 340, height: 60)
        .background(Color(red: 0, green: 0, blue: 0).opacity(0.05))
        .cornerRadius(20)
        .offset(x: 0, y: -278)
        Text("Home - CosechiOS Guide")
          .font(Font.custom("Inria Sans", size: 30).weight(.bold))
          .foregroundColor(.black)
          .offset(x: 0, y: -338.50)
        Text("Categories")
          .font(Font.custom("Inria Sans", size: 20))
          .foregroundColor(.black)
          .offset(x: -40, y: -217)
        Text("Difficulty")
          .font(Font.custom("Inria Sans", size: 20))
          .foregroundColor(.black)
          .offset(x: -40, y: -19)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 150, height: 35)
          .background(.black)
          .cornerRadius(10)
          .offset(x: -95, y: -171.50)
        Text("All Crops")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.white)
          .offset(x: -84, y: -172)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 150, height: 35)
          .background(.white)
          .cornerRadius(10)
          .overlay(
            RoundedRectangle(cornerRadius: 10)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: -95, y: -123.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 150, height: 35)
          .background(.white)
          .cornerRadius(10)
          .overlay(
            RoundedRectangle(cornerRadius: 10)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: -95, y: -75.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 60, height: 35)
          .background(.black)
          .cornerRadius(10)
          .offset(x: -140, y: 25.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 75, height: 35)
          .background(.white)
          .cornerRadius(10)
          .overlay(
            RoundedRectangle(cornerRadius: 10)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: -57.50, y: 25.50)
      };Group {
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 75, height: 35)
          .background(.white)
          .cornerRadius(10)
          .overlay(
            RoundedRectangle(cornerRadius: 10)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: 142.50, y: 25.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 95, height: 35)
          .background(.white)
          .cornerRadius(10)
          .overlay(
            RoundedRectangle(cornerRadius: 10)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: 42.50, y: 25.50)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 150, height: 35)
          .background(.white)
          .cornerRadius(10)
          .overlay(
            RoundedRectangle(cornerRadius: 10)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: 90, y: -123.50)
        Text("Herbs")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.black)
          .offset(x: -84, y: -125)
        Text("Fruits")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.black)
          .offset(x: 103, y: -125)
        Text("Flowers")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.black)
          .offset(x: -84, y: -77)
        Text("All")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.white)
          .offset(x: -141, y: 25.50)
        Text("Easy")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.black)
          .offset(x: -58, y: 25.50)
        Text("Hard")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.black)
          .offset(x: 143, y: 25.50)
        Text("Medium")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.black)
          .offset(x: 41.50, y: 25.50)
      };Group {
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 150, height: 35)
          .background(.white)
          .cornerRadius(10)
          .overlay(
            RoundedRectangle(cornerRadius: 10)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: 90, y: -171.50)
        Text("Vegetables")
          .font(Font.custom("Inria Sans", size: 20).weight(.bold))
          .foregroundColor(.black)
          .offset(x: 103, y: -172)
        ZStack() {

        }
        .frame(width: 24, height: 24)
        .offset(x: -146, y: -171)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 340, height: 150)
          .background(.white)
          .cornerRadius(20)
          .overlay(
            RoundedRectangle(cornerRadius: 20)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: 0, y: 179)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 340, height: 150)
          .background(.white)
          .cornerRadius(20)
          .overlay(
            RoundedRectangle(cornerRadius: 20)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: 0, y: 358)
      };Group {
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 150, height: 150)
          .background(Color(red: 0.50, green: 0.23, blue: 0.27).opacity(0.50))
          .cornerRadius(20)
          .offset(x: -95, y: 179)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 150, height: 150)
          .background(Color(red: 0.50, green: 0.23, blue: 0.27).opacity(0.50))
          .cornerRadius(20)
          .offset(x: -95, y: 358)
        Text("Versatile and rewarding to grow, tomatoes are perfect for beginners and experienced gardeners alike.")
          .font(Font.custom("Inria Sans", size: 12))
          .foregroundColor(.black)
          .offset(x: 72.50, y: 166)
        Text("Fast-growing leafy green that´s perfect for continuous harvesting and succession planting.")
          .font(Font.custom("Inria Sans", size: 12))
          .foregroundColor(.black)
          .offset(x: 68, y: 346)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 60, height: 20)
          .background(Color(red: 0.97, green: 1, blue: 0))
          .cornerRadius(5)
          .overlay(
            RoundedRectangle(cornerRadius: 5)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: -128, y: 128)
        Rectangle()
          .foregroundColor(.clear)
          .frame(width: 60, height: 20)
          .background(Color(red: 0, green: 1, blue: 0.83))
          .cornerRadius(5)
          .overlay(
            RoundedRectangle(cornerRadius: 5)
              .inset(by: 1)
              .stroke(Color(red: 0, green: 0, blue: 0).opacity(0.50), lineWidth: 1)
          )
          .offset(x: -128, y: 308)
      };Group {
        Text("Medium")
          .font(Font.custom("Inria Sans", size: 12).weight(.bold))
          .foregroundColor(.black)
          .offset(x: -128.50, y: 126.50)
        Text("Easy")
          .font(Font.custom("Inria Sans", size: 12).weight(.bold))
          .foregroundColor(.black)
          .offset(x: -128.50, y: 306.50)
      }
    }
    .frame(width: 402, height: 874)
    .background(.white)
    .cornerRadius(20);
  }
}

#Preview {
    Home()
        .modelContainer(for: Item.self, inMemory: true)
}
